version: '3.8'

services:
  web:
    depends_on:
      - api
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: social-app
    develop:
      watch:
        - path: ./web-app/package.json
          action: rebuild
        - path: ./web-app/yarn.lock
          action: rebuild
        - path: ./web-app
          target: /
          action: sync

  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    container_name: social-app-api
    develop:
      watch:
        - path: ./api/package.json
          action: rebuild
        - path: ./api/yarn.lock
          action: rebuild
        - path: ./api
          target: /
          action: sync

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    container_name: social-app-db
    volumes:
      - social-app:/data/db

volumes:
  social-app:
